import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState, useEffect, useCallback } from 'react';

export default function Home() {

  const scrollWeightAmount = 4;
  const [imageSequence, setImageSequence] = useState<number>(1);
  //const [scrollPos, setScrollPos] = useState<number>(0);
  const [scrollWeight, setScrollWeight] = useState<number>(0);

  const scroll = useCallback((event: Event) => {
    //setScrollPos(window.scrollY);
    //console.log('fired');
    console.log('weight is '+scrollWeight);
    if(scrollWeight >= scrollWeightAmount) {
      setScrollWeight(0);
    } else {
      setScrollWeight(currentScrollWeight => currentScrollWeight + 1);
    }
  }, [setScrollWeight, scrollWeight]);

   useEffect(() => {
    window.addEventListener('mousewheel', scroll);
    return () => {
      window.removeEventListener('mousewheel', scroll);
    };
  }, [scroll]);

  useEffect(() => {
    //console.log(imageSequence);
    //console.log(scrollWeight);
    /*if(scrollPos >= 1600) {
      setImageSequence(Math.floor((scrollPos - 1500) / 10));
    }*/

  });

  useEffect(() => {
    if(scrollWeight >= (scrollWeightAmount - 1)) {
      if(imageSequence < 60) {
        setImageSequence(currentImageSequence => currentImageSequence + 1);
      }
    }
    console.log(scrollWeight);
  }, [setImageSequence, scrollWeight]);
  

  const click = () => {
    if(imageSequence < 60) {
      setImageSequence(imageSequence + 1);
    }
    console.log(imageSequence);
  }

  return (
    <div className={styles.container} onClick={click}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.imageContainer}>
        <img src="/frontPage.jpg" className={styles.headImage} />
        <button className={styles.Shop}>Shop</button>
      </div>
      <div className={styles.skateShow}>
        <div className={styles.board1}>
          <img src="/croppedSkateboardBottom.png" className={styles.skateboardBottom1}/>
          <p className={styles.boardDesc}>The highest quality, stringed wood boards.<br/>
          Made to skate by the pros</p>
        </div>
        <div className={styles.board2}>
          <img src="/skateboardTop.png" className={styles.skateboardTop}/>
          <p className={styles.boardDesc}>Profesionally shaped, structurally sound. Made for you</p>
        </div>
        <div className={styles.board3}>
          <img src="/skateboardBottom2.png" className={styles.skateboardBottom2}/>
          <p className={styles.boardDesc}>Custom designs</p>
        </div>
      </div>
      <div className={styles.cropFit}>
        <div className={styles.cropTop} />
        <img src="side.jpg" className={styles.sidePic} />
        <div className={styles.cropFitInfo}>
          <p className={styles.worlds1}>Worlds #1 skate brand</p>
          <button className={styles.visit}>Visit our skaters</button>
        </div>
      </div>
      <div className={styles.spinBoard} >
        <img src={"/skateboard-anim/"+String(imageSequence).padStart(4, '0')+".png"} className={styles.skateAnim} />
        <p className={styles.qoute}>Made with perfection</p>
      </div>
      <div className={styles.sampleDiv} />
    </div>
  )
}


/*export async function getStaticProps() {
  for(let i = 0; i < 60; i++) {
    const 
  }
}*/