import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.imageContainer}>
        <img src="/frontPage.jpg" className={styles.headImage} />
        <button className={styles.Shop}>Shop</button>
      </div>
      <div className={styles.skateShow}>
        <div className={styles.board1}>
          <img src="/croppedSkateboardBottom.png" className={styles.skateboardBottom1}/>
          <p className={styles.boardDesc}>The highest quality, stringed wood boards.<br/>
          Made to skate by the pros</p>
        </div>
        <div className={styles.board2}>
          <img src="/skateboardTop.png" className={styles.skateboardTop}/>
          <p className={styles.boardDesc}>Proffesionally shaped, structuraly sound. Made for you</p>
        </div>
        <div className={styles.board3}>
          <img src="/skateboardBottom2.png" className={styles.skateboardBottom2}/>
          <p className={styles.boardDesc}>Custom designs</p>
        </div>
      </div>
      <div className={styles.cropFit}>
        <div className={styles.cropTop} />
        <img src="side.jpg" className={styles.sidePic} />
        <div className={styles.cropFitInfo}>
          <p className={styles.worlds1}>Worlds #1 skate brand</p>
          <button className={styles.visit}>Visit our skaters</button>
        </div>
      </div>
      <div className={styles.sampleDiv} />
    </div>
  )
}
//<div className={styles.cropBottom} />